
server:
  port: 8080
spring:
  application:
    name: web-app

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/userweb
    username: root
    password: spttek
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update



eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8100/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}