
server:
  port: 8888
#使用本地的配置文件
spring:
  profiles:
    active: native
  application:
    name: config-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8100/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
