
server:
  port: 8888
spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
   config:
    server:
     git:
       uri: https://github.com/15807552923/springcloudconfig.git
       search-paths: /**
    label: master
    username: 15807552923
    password: 0061penel.com

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8100/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
